column.count =11
 
column.0.label    = Question Text
column.0.field    = questionDetail
column.0.required = true
column.0.type     = String
 
column.1.label    = Question Type
column.1.field    = questionTypeId
column.1.required = true
column.1.type     = String
 
column.2.label    = Topic Id
column.2.field    = topicId
column.2.required = true
column.2.type     = String
 
column.3.label    = Option A
column.3.field    = optionA
column.3.required = true
column.3.type     = String
 
column.4.label    = Option B
column.4.field    = optionB
column.4.required = true
column.4.type     = String
 
column.5.label    = Option C
column.5.field    = optionC
column.5.required = false
column.5.type     = String
 
column.6.label    = Option D
column.6.field    = optionD
column.6.required = false
column.6.type 	  = String
 
column.7.label    = Answer
column.7.field    = answer
column.7.required = true
column.7.type 	  = String
 
column.8.label    = Num Of Answers
column.8.field    = numAnswers
column.8.required = true
column.8.type     = Number
 
column.9.label    = Difficulty Level
column.9.field    = difficultyLevel
column.9.required = false
column.9.type     = Number
 
 
column.10.label    = Answer Value
column.10.field    = answerValue
column.10.required = false
column.10.type     = Number